import type { NotificationItem, Post } from "./types";

/** Helper to build lime placeholder photos until real uploads exist. */
function placeholderPhotos(postId: string, count: number) {
  return Array.from({ length: count }, (_, i) => ({
    id: `${postId}-photo-${i + 1}`,
    alt: `${postId} photo ${i + 1}`,
  }));
}

export const POSTS: Post[] = [
  {
    id: "post-1",
    author: { id: "user-russel", name: "Russel" },
    postedAt: "2026-10-07T11:00:00Z",
    postedAgo: "2 hours ago",
    text: "Hi everyone, today I was on the most beautiful mountain in the world, I also want to say hi to Silena, Olya and Davis!",
    photos: placeholderPhotos("post-1", 1),
    views: 1000,
    likes: 1000,
    liked: false,
    comments: [
      {
        id: "post-1-c1",
        author: { id: "user-1", name: "User" },
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        createdAt: "2026-10-07T11:20:00Z",
        postedAgo: "2 hours ago",
        likes: 1000,
        liked: false,
      },
      {
        id: "post-1-c2",
        author: { id: "user-2", name: "User" },
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        createdAt: "2026-10-07T11:40:00Z",
        postedAgo: "2 hours ago",
        likes: 1000,
        liked: false,
      },
      {
        id: "post-1-c3",
        author: { id: "user-3", name: "User" },
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        createdAt: "2026-10-07T11:55:00Z",
        postedAgo: "2 hours ago",
        likes: 1000,
        liked: false,
      },
    ],
  },
  {
    id: "post-2",
    author: { id: "user-silena", name: "Silena" },
    postedAt: "2026-10-07T10:00:00Z",
    postedAgo: "3 hours ago",
    text: "Two shots from yesterday's sunset hike — golden hour never disappoints.",
    photos: placeholderPhotos("post-2", 2),
    views: 640,
    likes: 312,
    liked: false,
    comments: [],
  },
  {
    id: "post-3",
    author: { id: "user-olya", name: "Olya" },
    postedAt: "2026-10-07T08:00:00Z",
    postedAgo: "5 hours ago",
    text: "Studio day! Three frames from the campus zine shoot.",
    photos: placeholderPhotos("post-3", 3),
    views: 480,
    likes: 156,
    liked: true,
    comments: [],
  },
  {
    id: "post-4",
    author: { id: "user-davis", name: "Davis" },
    postedAt: "2026-10-07T05:00:00Z",
    postedAgo: "8 hours ago",
    text: "Hackathon squad progress dump. Four screens, zero sleep.",
    photos: placeholderPhotos("post-4", 4),
    views: 2200,
    likes: 890,
    liked: false,
    comments: [],
  },
  {
    id: "post-5",
    author: { id: "user-russel", name: "Russel" },
    postedAt: "2026-10-06T13:00:00Z",
    postedAgo: "1 day ago",
    text: "Full gallery from the weekend trip — tap the last tile for the rest.",
    photos: placeholderPhotos("post-5", 6),
    views: 3400,
    likes: 1500,
    liked: false,
    comments: [],
  },
];

/** Mock notifications (Figma 515:150) — mixed read/unread so the tabs filter visibly. */
export const NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-1",
    title: "New comment on a project",
    body: "Russel commented in SME Cashier App",
    createdAt: "2026-10-07T14:12:00Z",
    read: false,
    link: "/collaborations/collab-1",
    // Frontend extension fields (rich-row rendering without parsing title):
    actor: { id: "user-russel", name: "Russel" },
    action: "commented in",
    target: "SME Cashier App",
    timeLabel: "Friday 3.12 PM",
    agoLabel: "2 hours ago",
  },
  {
    id: "notif-2",
    title: "New comment on a project",
    body: "Silena commented in Campus Event Portal",
    createdAt: "2026-10-07T13:40:00Z",
    read: false,
    link: "/collaborations/collab-4",
    actor: { id: "user-silena", name: "Silena" },
    action: "commented in",
    target: "Campus Event Portal",
    timeLabel: "Friday 1.40 PM",
    agoLabel: "4 hours ago",
  },
  {
    id: "notif-3",
    title: "Mentioned you",
    body: "Olya mentioned you in Portfolio Review",
    createdAt: "2026-10-05T18:05:00Z",
    read: true,
    link: "/collaborations/collab-3",
    actor: { id: "user-olya", name: "Olya" },
    action: "mentioned you in",
    target: "Portfolio Review",
    timeLabel: "Thursday 6.05 PM",
    agoLabel: "1 day ago",
  },
  {
    id: "notif-4",
    title: "Project invite",
    body: "Davis invited you to Hackathon Squad",
    createdAt: "2026-10-04T10:22:00Z",
    read: true,
    link: "/collaborations/collab-5",
    actor: { id: "user-davis", name: "Davis" },
    action: "invited you to",
    target: "Hackathon Squad",
    timeLabel: "Wednesday 10.22 AM",
    agoLabel: "2 days ago",
  },
];